// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4gz0fnLAahUzCSfpJMFkLnJ_sIGgzChI',
    appId: '1:37691429913:android:b370e514e4fed866824688',
    messagingSenderId: '37691429913',
    projectId: 'd-wallet-dd0ba',
    storageBucket: 'd-wallet-dd0ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3Fhx4LEQUs1ENsQz7SFmXDYZFMNyy6Vg',
    appId: '1:37691429913:ios:0e86ef113a5a166e824688',
    messagingSenderId: '37691429913',
    projectId: 'd-wallet-dd0ba',
    storageBucket: 'd-wallet-dd0ba.appspot.com',
    androidClientId: '37691429913-l8jtfij39gvnfe19b701qohep6om5rvr.apps.googleusercontent.com',
    iosClientId: '37691429913-9hu6ql91mf9c7vojlpa8qp9ne7b1bddi.apps.googleusercontent.com',
    iosBundleId: 'com.napaglobal.flutterBlocBaseSourceCode',
  );
}
